# Generated by Django 3.0.6 on 2020-08-21 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction_listings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.CharField(max_length=500)),
                ('product_title', models.CharField(max_length=40)),
                ('product_description', models.CharField(max_length=1000)),
                ('product_category', models.CharField(choices=[('Art', 'Art'), ('Cars', 'Cars'), ('Clothes', 'Clothes'), ('Games', 'Games'), ('Health & Beauty', 'Health & Beauty'), ('Home', 'Home'), ('Literature', 'Literature'), ('Music', 'Music'), ('Puzzle', 'Puzzle'), ('Science', 'Science'), ('Sports', 'Sports'), ('Technology', 'Technology'), ('Toys', 'Toys'), ('Others', 'Others')], default='Others', max_length=30)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_closed', models.BooleanField(default=False)),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('username', models.ForeignKey(default='david', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auctions.Auction_listings')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('content', models.CharField(max_length=350)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.Auction_listings')),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('bid_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('auction_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.Auction_listings')),
            ],
        ),
    ]
