# Generated by Django 3.0.6 on 2020-09-03 09:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20200903_0540'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.IntegerField(default=0)),
                ('user', models.ManyToManyField(blank=True, related_name='user_like', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
